name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    # Installe l'Android SDK + accepte les licences
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    # Installe Gradle 8.7 (compatible AGP 8.4.x) et active le cache
    - name: Set up Gradle 8.7
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.7

    # Lance la build avec Gradle (pas ./gradlew)
    - name: Build Debug APK
      run: gradle :app:assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: GD01CardBrowser-debug
        path: app/build/outputs/apk/debug/app-debug.apk
